Flask/src/views/auth_view.py
from flask import Blueprint, render_template, redirect, url_for, request, session
from facades.auth_facade import AuthFacade
from models.client_error import ValidationError, AuthError
from models.role_model import RoleModel

auth_blueprint = Blueprint("auth_view", __name__)

facade = AuthFacade()

@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    try:
        if request.method == "GET": return render_template("register.html", active="register", user={})
        facade.register()
        return redirect(url_for("vacations_view.vacations"))
    except ValidationError as err:
        return render_template("register.html", error = err.message, user = err.model)
    

@auth_blueprint.route("/login", methods=["GET", "POST"])
def login():
    try:
        if request.method == "GET":
            session.clear() # when you go from the url to login page, you logging out.
            err = request.args.get("error")
            return render_template("login.html", error = err, credentials={})
        facade.login()
        user = session.get("current_user")
        if user["role_id"] == RoleModel.User.value: # based on role_id, redirecting to the relevant page
            return redirect(url_for("vacations_view.vacations"))
        return redirect(url_for("vacations_view.admin"))
    except (ValidationError, AuthError) as err:
        return render_template("login.html", error = err.message, credentials = err.model)
    
@auth_blueprint.route("/logout")
def logout():
    try:
        facade.block_anonymous()
        facade.logout()
        return redirect(url_for("auth_view.login"))
    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message))

Flask/src/views/home_view.py
from flask import Blueprint, render_template

home_blueprint = Blueprint("home_view", __name__)

@home_blueprint.route("/")
@home_blueprint.route("/home")
def home():
    return render_template("home.html", active="home")


Flask/src/views/like_view.py
from flask import Blueprint, redirect, url_for, render_template
from facades.like_facade import LikesFacade
from facades.auth_facade import AuthFacade
from models.client_error import AuthError, ResourceNotFoundError

like_blueprint=Blueprint("like_view", __name__)
@like_blueprint.route("/like/<int:vacation_id>")
def handle_like(vacation_id):
    try:
        auth_facade = AuthFacade()
        like_facade = LikesFacade()
        auth_facade.block_admin()
        auth_facade.block_anonymous()
        like_facade.handle_like(vacation_id)
        return redirect(url_for("vacations_view.vacations"))
    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message))
    except ResourceNotFoundError as err:
        return render_template("404.html", error=err.message)

Flask/src/views/vacations_view.py
from flask import Blueprint, render_template, redirect, url_for, request, send_file, session
from facades.vacation_facade import VacationFacade
from utils.image_handler import ImageHandler
from models.client_error import ValidationError, AuthError, ResourceNotFoundError
from facades.auth_facade import AuthFacade
from utils.flag_handler import FlagHandler

vacations_blueprint = Blueprint("vacations_view", __name__)
vacation_facade = VacationFacade()
auth_facade = AuthFacade()

@vacations_blueprint.route("/vacations/images/<string:image_name>")
def get_image(image_name):
    image_path = ImageHandler.get_image_path(image_name)
    return send_file(image_path)

@vacations_blueprint.route("/vacations")
def vacations():
    try:
        err = request.args.get("error")
        auth_facade.block_anonymous()
        auth_facade.block_admin()
        all_vacations = vacation_facade.get_all_vacations()
        liked_vacations_ids = vacation_facade.get_liked_vacations_ids()
        return render_template("vacations.html", vacations=all_vacations, ids = liked_vacations_ids, error = err, active="vacations")
    except AuthError as err:
        user = session.get("current_user")
        if not user:
            return redirect(url_for("auth_view.login", error = err.message))
        return redirect(url_for("vacations_view.admin", error = err.message))
    
@vacations_blueprint.route("/admin")
def admin():
    try:
        err = request.args.get("error")
        auth_facade.block_anonymous()
        auth_facade.block_non_admin()
        all_vacations = vacation_facade.get_all_vacations()
        return render_template("admin.html", vacations = all_vacations, error = err, active="admin")
    except AuthError as err:
        user = session.get("current_user")
        if not user:
            return redirect(url_for("auth_view.login", error = err.message))
        return redirect(url_for("vacations_view.vacations", error = err.message))

@vacations_blueprint.route("/vacations/new", methods=["GET", "POST"])
def insert():
    try:
        auth_facade.block_anonymous()
        auth_facade.block_non_admin()
        all_countries = vacation_facade.get_all_countries()
        countries_with_flags_classes = FlagHandler.get_countries_with_flags_classes()
        if request.method =="GET":
            return render_template("insert.html", countries = countries_with_flags_classes, active="insert")
        vacation_facade.add_vacation()
        return redirect(url_for("vacations_view.admin"))
    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message))
    except ValidationError as err:
        return render_template("insert.html",error=err.message, countries = all_countries, active = "insert")

@vacations_blueprint.route("/vacations/edit/<int:id>", methods=["GET", "POST"])
def edit(id):
    try:
        auth_facade.block_anonymous()
        auth_facade.block_non_admin()
        if request.method == "GET":
            one_vacation = vacation_facade.get_one_vacation(id)
            countries_with_flags_classes = FlagHandler.get_countries_with_flags_classes()
            return render_template("edit.html", vacation=one_vacation, countries=countries_with_flags_classes, active="edit")
        vacation_facade.update_vacation()
        return redirect(url_for("vacations_view.admin"))
    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message))
    except ResourceNotFoundError as err:
        return render_template("404.html", error=err.message)
    except ValidationError as err:
        return render_template("edit.html",error=err.message, vacation=err.model)

@vacations_blueprint.route("/vacations/delete/<int:id>")
def delete(id):
    auth_facade.block_anonymous()
    auth_facade.block_non_admin()
    try:
        vacation_facade.delete_vacation(id)
        return redirect(url_for("vacations_view.admin"))
    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message))
    except ResourceNotFoundError as err:
        return render_template("404.html", error=err.message)
    

Flask/src/templates/admin.html
{% extends "layout.html" %}

{% block title %}
Vacations Agency | Vacations
{% endblock title %}

{% block content %}

<h1>Vacations</h1>
<hr>

{% for v in vacations %}
<div class="vacation-card">
    <img class="vacation-image" src="{{url_for('vacations_view.get_image', image_name=v.image if v.image else '---')}}">
        <h2 class="country-name">
            <img src="{{ url_for('static', filename='images/flags/' + v.country_name | lower + '.png') }}" class="flag-icon-card">
            {{v.country_name}}            
        </h2>
        <a class="edit-button" href="{{url_for('vacations_view.edit', id = v.vacation_id)}}">✏️edit</a>
        <a onclick="confirmDelete()" class="delete-button" href="{{url_for('vacations_view.delete', id = v.vacation_id)}}">🗑️delete</a>
    <div class="vacation-date">📅 {{v.start_date}} - {{v.end_date}}</div>
    <div class="vacation-description">{{v.description}}</div>
    <div class="vacation-price">{{v.price}} $</div>
</div>
{% endfor %}

{% endblock content %}

Flask/src/templates/auth.html
<div>
    {% if user %}
    <span>
        Hi, {{ user.first_name }} {{ user.last_name }}!
    </span>
    <span>
        |
    </span>
    <a href="{{url_for('auth_view.logout')}}">Log out</a>
    {% else %}
        <span>
            Hello, guest!
        </span>
        <span>
            |
        </span>
        <a href="{{url_for('auth_view.login')}}">Log in</a>
        <span>
            |
        </span>
        <a href="{{url_for('auth_view.register')}}">Register</a>
    {% endif %}
</div>

Flask/src/templates/edit.html
{% extends "layout.html" %}

{% block title %}
Vacations Agency | Edit Vacation
{% endblock title %}


{% block content %}
<h2>Edit Vacation</h2>

<form method="post" class="fancy_form" required enctype="multipart/form-data">
    <input type="hidden" name="id" value="{{vacation.vacation_id}}">
    <label for="country">Country:</label>
    <div class="dropdown">
        <button class= "btn btn-secondary dropdown-toggle" aria-expanded="false" type="button" data-bs-toggle="dropdown" id="countryDropdown"> Select a Country</button>
        <ul class="dropdown-menu" aria-labelledby="countryDropdown">
            {% for c in countries %}
            <li>
                <a href="#" class="dropdown-item" data-value="{{c[0]}}">
                    <span class="flag-icon {{c[1]}}"></span>&nbsp;{{c[0]}}
                </a>
            </li>
            {% endfor %}
        </ul>
        <input type="hidden" name="country" id="country-input">
    </div>
    <br><br>
    <label>Description:</label>
    <input type="text" name="description" value="{{vacation.description}}" required class="form-control" minlength="3"> 

    <label>Start Date:</label>
    <input type="date" name="start_date" value="{{vacation.start_date}}" required class="form-control">

    <label>End Date:</label>
    <input type="date" name="end_date" value="{{vacation.end_date}}" required class="form-control">

    <label>Price:</label>
    <input type="number" name="price" value="{{vacation.price}}" required class="form-control" min="0" max="10000"> 

    <label>Image:</label>
    <img class="edit-image" src="{{url_for('vacations_view.get_image', image_name=(vacation.image if vacation.image else '---'))}}">
    <input type="file" name="image" class="form-control"  accept="image/*">

    <button class="btn btn-primary w-100">Save</button>
    <br><br>
    <a href="{{url_for('vacations_view.admin')}}" class="btn w-100 cancel-button">Cancel</a>
</form>
{% endblock content %}
 

Flask/src/templates/home.html
{% extends "layout.html" %}

{% block title %}
Vacations Agency | Home
{% endblock title %}

{% block content %}

<h1>Welcome to Vacations Agency Website!</h1>
<hr>
<h2>About our company:</h2>
<h4>
    Discover your dream getaway with our vacation agency!<br>
    We specialize in crafting personalized travel experiences, offering everything from serene beach retreats <br>
    to adventurous mountain excursions. Our dedicated team ensures every detail is perfect, so you can relax <br>
    and enjoy your trip. Let us turn your vacation dreams into reality.<br>
    Explore, unwind, and create unforgettable memories.
</h4>
<img class="home-image"src="{{ url_for('static', filename='images/airplane.png') }}">
<h6> Contact us:<br>
📞 03-7843866 | 📧 vacations@agency.com
</h6>
{% endblock content %}

Flask/src/templates/insert.html
{% extends "layout.html" %}

{% block title %}
Vacations Agency | Add Vacation
{% endblock title %}


{% block content %}
<h2>Add Vacation</h2>

<form method="post" class="fancy_form" required enctype="multipart/form-data">
    <label for="country">Country:</label>
    <div class="dropdown">
        <button class= "btn btn-secondary dropdown-toggle" aria-expanded="false" type="button" data-bs-toggle="dropdown" id="countryDropdown"> Select a Country</button>
        <ul class="dropdown-menu" aria-labelledby="countryDropdown">
            {% for c in countries %}
            <li>
                <a href="#" class="dropdown-item" data-value="{{c[0]}}">
                    <span class="flag-icon {{c[1]}}"></span>&nbsp;{{c[0]}}
                </a>
            </li>
            {% endfor %}
        </ul>
        <input type="hidden" name="country" id="country-input">
    </div>
    <br>
    <label>Description:</label>
    <input type="text" name="description" required class="form-control" minlength="3"> 

    <label>Start Date:</label>
    <input type="date" name="start_date" required class="form-control">

    <label>End Date:</label>
    <input type="date" name="end_date" required class="form-control">

    <label>Price:</label>
    <input type="number" name="price" required class="form-control" min="0" max="10000"> 

    <label>Image:</label>
    <input type="file" name="image" accept="image/*" required class="form-control">

    <button class="btn btn-primary w-100">Add</button>
    <br><br>
    <a href="{{url_for('vacations_view.admin')}}" class="btn w-100 cancel-button">Cancel</a>
</form>
{% endblock content %}
 

Flask/src/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.4.6/css/flag-icon.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock title %}</title>
    <!-- adding the logo to the tab -->
    <link rel="icon" href="/static/images/favicon.ico">
</head>

<body>
    <!-- import user for later use -->
    {% set user = session.get("current_user") %}
    <div class="layout">
        <header>
            {% include "nav.html" %}
        </header>

        <main>
            {% block content %}
            {% endblock content %}
            {% if error %} <span class="error">{{error}}</span> {% endif %}
        </main>

        <footer>
            <marquee>Dor Ziv - All Rights Reserved®</marquee>
        </footer>
    </div>
<script src="{{url_for('static', filename='js/main.js')}}"></script>
<!-- can be placed in the top of the HTML code, using script 'defer' -->
</body>

</html>

Flask/src/templates/login.html
{% extends "layout.html" %}

{% block title %}
Vacations Agency | Login
{% endblock title %}

{% block content %}
<h1>Login</h1>
<hr>

<form method="post" class="fancy_form">
    <label>Email:</label>
    <input type="email" value="{{credentials.email}}" name="email" class="form-control" required minlength="2" maxlength="100">
    <br>
    <label>Password:</label>
    <input type="password" value="{{credentials.password}}" name="password" class="form-control" required minlength="4" maxlength="100">
    <br>
    <button class="btn btn-primary w-100">Log in</button>
    <br><br>
    <div class="account">
        <div>Don't have an account?</div>
        <a href="{{url_for('auth_view.register')}}">Register</a>
    </div>    
</form>
{% endblock content %}

Flask/src/templates/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a href="{{ url_for('home_view.home') }}" class="image-link">
            <img src="{{ url_for('static', filename='/images/favicon.ico') }}" width="80" height="40">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <span>&nbsp;</span>
                <li>
                    <a aria-current="page" href="{{ url_for('home_view.home') }}"{%  if active=='home' %} class='active' {% endif %}>Home</a>
                </li>
                <span>&nbsp;|&nbsp;</span>
                {% if user["role_id"] == 2 %}
                <li>
                    <a href="{{ url_for('vacations_view.vacations') }}"{%  if active=='vacations' %} class='active' {% endif %}>Vacations</a>
                </li>
                {% endif %}
                {% if user["role_id"] == 1 %}
                <li>
                    <a href="{{ url_for('vacations_view.insert') }}"{%  if active=='insert' %} class='active' {% endif %}>Add Vacation</a>
                </li>
                <span>&nbsp;|&nbsp;</span>
                <li>
                    <a href="{{ url_for('vacations_view.admin') }}"{%  if active=='admin' %} class='active' {% endif %}>Admin Page</a>
                </li>
                {% endif %}

            </ul>
            <div>
                {% include "auth.html" %}
            </div>
        </div>
    </div>
</nav>

Flask/src/templates/register.html
{% extends "layout.html" %}

{% block title %}
Vacations Agency | Register
{% endblock title %}

{% block content %}

<h1>Register</h1>
<hr>

<form method="post" class="fancy_form">
    <label>First Name: </label>
    <input type="text" name="first_name" required value="{{user.first_name}}" class="form-control" minlength="2" maxlength="100">
    <br>
    <label>Last Name:</label>
    <input type="text" name="last_name" required value="{{user.last_name}}" class="form-control" minlength="3" maxlength="100">
    <br>
    <label>Email:</label>
    <input type="email" name="email" required value="{{user.email}}" class="form-control" minlength="2" maxlength="100">
    <br>
    <label>Password:</label>
    <input type="password" name="password" required value="{{user.password}}" class="form-control" minlength="4" maxlength="100">
    <br>
    <button class="btn btn-primary w-100">Register</button>
    <br><br>
    <div class="account">
        <div>Already have an account?</div>
        <a href="{{url_for('auth_view.login')}}">Login</a>
    </div> 
</form>

{% endblock content %}

Flask/src/templates/vacations.html
{% extends "layout.html" %}

{% block title %}
Vacations Agency | Vacations
{% endblock title %}

{% block content %}

<h1>Vacations</h1>
<hr>

{% for v in vacations %}
<div class="vacation-card">
    <img class="vacation-image" src="{{url_for('vacations_view.get_image', image_name=v.image if v.image else '---')}}">
        <h2 class="country-name">
            <img src="{{ url_for('static', filename='images/flags/' + v.country_name | lower + '.png') }}" class="flag-icon-card">
            {{v.country_name}}
        </h2>
        {% if v.vacation_id in ids %}
        <a class="red-btn" href="{{url_for('like_view.handle_like', vacation_id = v.vacation_id)}}"> ❤️ {{v.likes_count}} Like </a>
        {% else %}
        <a class="white-btn" href="{{url_for('like_view.handle_like', vacation_id = v.vacation_id)}}"> 🩶 {{v.likes_count}} Like </a>
        {% endif %}
    <div class="vacation-date">📅 {{v.start_date}} - {{v.end_date}}</div>
    <div class="vacation-description">{{v.description}}</div>
    <div class="vacation-price">{{v.price}} $</div>
</div>
{% endfor %}

{% endblock content %}